### ISSUE TITLE
'_Complex' requires a type specifier; assuming '_Complex double'

### ISSUE THREAD

**Issue by bohboh10** [sevagh/libxcorr#1]
Hi,

trying to install the library on osx. During the make, I got this error:
[ 33%] Building C object CMakeFiles/xcorr.dir/src/timedomain.c.o
/Users/andrea/vm/voicedetection/test_libraries/pitch-detection/libxcorr/src/timedomain.c:10:3: error:
      plain '_Complex' requires a type specifier; assuming '_Complex double'
      [-Werror]
                complex acf = 0 + 0*I;
                ^
                        double
/usr/include/complex.h:37:17: note: expanded from macro 'complex'
#define complex _Complex
                ^
/Users/andrea/vm/voicedetection/test_libraries/pitch-detection/libxcorr/src/timedomain.c:13:10: error:
      plain '_Complex' requires a type specifier; assuming '_Complex double'
      [-Werror]
                        const complex conjb = conj(((complex*)signalb)[i]);
                              ^
                                      double
/usr/include/complex.h:37:17: note: expanded from macro 'complex'
#define complex _Complex
                ^
/Users/andrea/vm/voicedetection/test_libraries/pitch-detection/libxcorr/src/timedomain.c:13:33: error:
      plain '_Complex' requires a type specifier; assuming '_Complex double'
      [-Werror]
                        const complex conjb = conj(((complex*)signalb)[i]);
                                                     ^
                                                             double
/usr/include/complex.h:37:17: note: expanded from macro 'complex'
#define complex _Complex
                ^
/Users/andrea/vm/voicedetection/test_libraries/pitch-detection/libxcorr/src/timedomain.c:15:7: error:
      plain '_Complex' requires a type specifier; assuming '_Complex double'
      [-Werror]
                                ((complex*)signala)[signala_idx-N] : 1.0;
                                  ^
                                          double
/usr/include/complex.h:37:17: note: expanded from macro 'complex'
#define complex _Complex
                ^
/Users/andrea/vm/voicedetection/test_libraries/pitch-detection/libxcorr/src/timedomain.c:18:5: error:
      plain '_Complex' requires a type specifier; assuming '_Complex double'
      [-Werror]
                ((complex*)result)[tau] = acf;
                  ^
                          double
/usr/include/complex.h:37:17: note: expanded from macro 'complex'
#define complex _Complex
                ^
5 errors generated.

**Comment by sevagh** [comment]
Good catch! Fixed in the latest commit, can you try again?

**Comment by bohboh10** [comment]
libxcorr/src/fftw.c:6:10: fatal error:
      'fftw3.h' file not found
#include <fftw3.h>

**Comment by sevagh** [comment]
So, to use FFTW-based cross-correlation, you need FFTW3 (not sure how to install it on Mac OSX but it's the defacto Unix FFT library).

However, if you use `cmake -DNO_FFTW=ON` (like mentioned in the README), you can compile without the FFTW feature.

**Comment by bohboh10** [comment]
Ok installed fftw. NOw I got:
[ 33%] Building C object CMakeFiles/xcorr.dir/src/fftw.c.o
[ 66%] Linking C shared library libxcorr.dylib
clang: error: argument unused during compilation: '-ansi'
make[2]: *** [libxcorr.dylib] Error 1
make[1]: *** [CMakeFiles/xcorr.dir/all] Error 2
make: *** [all] Error 2

any idea?

**Comment by sevagh** [comment]
I've only tested this with gcc, not clang. I removed `-ansi` as it was useless anyway, you can try again if you pull.
